### PR TITLE
Create Chinese(Simplified) localization

### PR DESCRIPTION
**Pull request by ChromaPIE**
**Big fan of this marvelous TiC addon from China.**

It was so much fun to try translating a lang file containing so much voicelines from video games like OVERWATCH, DOTA2, LOL etc. and sentences from poetries of Shakespeare and Shelley, thinking about how to respect their origin meaning and meanwhile make players chuckle.

Tried my best to have all strings in the latest release translated into Simplified Chinese and hoping this localization can help introduce this awesome actively-updating addon of TiC to more players in our communities.

I'm sure to try my best to make the zh_cn localization up to date, just for hobby and fun, and I'd be appreciated if you would merge this PR. Thanks a lot.

### CODE REVIEW

**Comment by phantamanta44** [comment]
thanks for the work. i just noticed that i made a couple mistakes in the lang file, so i'll fix those quickly and you can make the analogous changes here

**Comment by phantamanta44** [comment]
see: 8293667

**Comment by ChromaPIE** [comment]
Done. And seems like a ''\n'' is missing in the Stonebound line after ''§r''？Already added in zh_cn.lang.

**Comment by phantamanta44** [comment]
yeah, i noticed after pushing... fixed it with a force-push lol

**Pull request merged**
